name: mycode
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/icon3.png
    - assets/images/apple.png
    - assets/images/google.png
    - assets/images/success.png
    - assets/images/home/laravel-course.jpg
    - assets/images/home/symfony-course.png
    - assets/images/home/falcon-course.png
    - assets/images/home/course1.jpeg
    - assets/images/home/course2.jpeg
    - assets/images/home/course3.jpg
    - assets/images/home/course4.png
    - assets/images/home/html.png
    - assets/images/home/css.png
    - assets/images/home/js.png
    - assets/images/home/php.png
    - assets/images/home/python.png